repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.6.1
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/sourcery-ai/sourcery
    rev: v1.35.0
    hooks:
    -   id: sourcery
        # * review only changed lines:
        # * omit the summary
        args: [--diff=git diff HEAD, --no-summary, one_updater/]

-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        args: ["--profile", "black"]

-   repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.6.14
    hooks:
    -   id: uv-lock
    -   id: uv-export

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
        args: [--unsafe]
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-toml
        # -   id: check-added-large-files
    -   id: check-ast
        # -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: debug-statements
        # -   id: requirements-txt-fixer
    -   id: mixed-line-ending

-   repo: https://github.com/sirwart/ripsecrets
    rev: v0.1.9
    hooks:
    -   id: ripsecrets

-   repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.88.23
    hooks:
    -   id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified
          --fail'
        language: system
        stages: ["pre-commit"]

    # Keep getting error about source flag missing so disabling
    # - repo: https://github.com/gitleaks/gitleaks
    #   rev: v8.19.0
    #   hooks:
    #     - id: gitleaks
    #       args: ["--verbose", "--source", "."]

    # enforce conventional commit messages
    # -   repo: https://github.com/compilerla/conventional-pre-commit
    #     rev: 'v2.4.0'
    #     hooks:
    #       - id: conventional-pre-commit
    #         stages: [commit-msg]
    #         args: [refactor, chore, build, ci, docs, feat, fix, test, perf, style, BREAKING_CHANGE]
