# One-Updater Default Configuration
# This is a minimal configuration file. You can enable additional package managers
# by adding them to this file. For a full list of supported package managers and
# their configurations, visit: https://github.com/TimothyBryant/one-updater

# Global configuration
verbose: false # Set to true to enable verbose output by default
logging:
  level: "INFO" # Can be DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(message)s"

package_managers:
  brew:
    enabled: true
    commands:
      update: ["brew", "update"]
      upgrade: ["brew", "upgrade"]

  apt:
    enabled: true
    commands:
      update: ["sudo", "apt-get", "update"]
      upgrade: ["sudo", "apt-get", "upgrade", "-y"]
# Add more package managers by copying their configuration from the documentation
# Example:
#   NPM - Node.js package manager
#   npm:
#     enabled: true
#     commands:
#       update: ["npm", "update", "-g"]
#       upgrade: ["npm", "upgrade", "-g"]
