# One-Updater Default Configuration
# This is a minimal configuration file. You can enable additional package managers
# by adding them to this file. For a full list of supported package managers and
# their configurations, visit: https://github.com/TimothyBryant/one-updater

# Global configuration
verbose: false # Set to true to enable verbose output by default
logging:
  level: "INFO" # Can be DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(message)s"

package_managers:
  # Homebrew - The missing package manager for macOS
  brew:
    enabled: true
    commands:
      update: ["brew", "update"]
      upgrade: ["brew", "upgrade"]

  # Pip - The Python package installer
  pip:
    enabled: true
    commands:
      update: [] # No separate update command needed
      upgrade: [] # Upgrade handled internally
    virtualenv: "/path/to/your/virtualenv"  # Optional: Path to virtualenv
    pyenv_version: "3.11.0"  # Optional: pyenv version to use

  # NPM - Node.js package manager
  npm:
    enabled: true
    commands:
      update: ["npm", "update", "-g"]
      upgrade: ["npm", "upgrade", "-g"]
# Add more package managers by copying their configuration from the documentation
# Example:
#   apt:
#     enabled: true
#     commands:
#       update: ["sudo", "apt-get", "update"]
#       upgrade: ["sudo", "apt-get", "upgrade", "-y"]
